### PR TITLE
Allow the resolution of 3ID DIDs

### PR DESCRIPTION
**Pull request by dysbulic**
The `ClaimMgr`'s `verifyJWS` method was configured to only resolve `key` DIDs. These changes add the ability to resolve IDX DIDs.

### CODE REVIEW

**Review by oed — APPROVED** [review]
Super, thanks!

**Comment by oed** [comment]
@dysbulic @pi0neerpat Any idea why tests are failing here?

**Comment by dysbulic** [comment]
> Any idea why tests are failing here?

@oed, it looks from the log like a missing Redis instance and a missing Twitter key.

**Comment by oed** [comment]
Alright, I'll merge this for now since it seems like the tests are broken in general.

**Pull request merged**
